from lightningblocks.dataaug.base_augment import BaseAugment
from lightningblocks.dataaug.word_delete import WordDelete
from lightningblocks.dataaug.word_insert import WordInsert
from lightningblocks.dataaug.word_substitute import WordSubstitute
from lightningblocks.dataaug.word_swap import WordSwap
